server:
  port: 8999

spring:
  application:
   name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USERSERVICE
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: InventoryService
          uri: lb://InventoryService
          predicates:
            - Path=/product/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
